'use strict';
const E=SquadEngine,$=id=>document.getElementById(id),c=$('game'),ctx=c.getContext('2d');let W=450,H=750,dpr=1,state=E.create(),level=1,unlocked=1,last=0,finished=false,pointer=null,sound=false,audio=null,keys=new Set();
try{unlocked=Math.max(1,Math.min(24,Number(localStorage.getItem('fire-squad-unlocked'))||1));level=unlocked;state=E.create(level)}catch{}
const images={};for(const name of ['soldier','enemy','boss','crate','barrel','turret']){images[name]=new Image();images[name].src='assets/'+name+'.webp'}
const region=['海港突围','沙岸攻坚','冰川防线','高空要塞'];
function resize(){const r=c.getBoundingClientRect();W=r.width;H=r.height;dpr=Math.min(window.devicePixelRatio||1,2);c.width=Math.round(W*dpr);c.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}window.addEventListener('resize',resize);resize();
function proj(x,d){let t=1/(1+Math.max(-2,d)*.052);return {x:W/2+x*W*.435*t,y:H*.14+H*.72*t,t}}
function poly(points,fill,stroke){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke()}}
function rect(x,y,w,h,color,r=6){ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function text(str,x,y,size=18,color='#fff'){ctx.font='900 '+Math.max(12,size)+'px system-ui,sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineWidth=3;ctx.strokeStyle='#17314c';ctx.strokeText(str,x,y);ctx.fillStyle=color;ctx.fillText(str,x,y)}
function sprite(name,x,y,width){const im=images[name];if(!im.complete||!im.naturalWidth)return;const h=width*im.naturalHeight/im.naturalWidth;ctx.drawImage(im,x-width/2,y-h,width,h)}
function drawRoad(){const grad=ctx.createLinearGradient(0,0,0,H);const ice=level>12&&level<=18;grad.addColorStop(0,ice?'#b6e9fa':'#90daf5');grad.addColorStop(1,ice?'#66b9d8':'#2383ba');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);const a=proj(-1.2,90),b=proj(1.2,90),l=proj(-1.2,-3),r=proj(1.2,-3);poly([[a.x,a.y+14],[b.x,b.y+14],[r.x,r.y+30],[l.x,l.y+30]],'#395470');poly([[a.x,a.y],[b.x,b.y],[r.x,r.y],[l.x,l.y]],ice?'#d5e7ed':'#d6dfe6');
 for(let j=0;j<20;j++){const d=j*7-(state.progress%7);if(d<0)continue;const q=proj(0,d),q2=proj(0,d+1.6);ctx.strokeStyle='#f7faffaa';ctx.lineWidth=Math.max(1,q.t*3);for(const x of [-.333,.333]){const p=proj(x,d),p2=proj(x,d+1.6);ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p2.x,p2.y);ctx.stroke()}ctx.strokeStyle='#829db933';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(proj(-1.18,d).x,q.y);ctx.lineTo(proj(1.18,d).x,q.y);ctx.stroke();}
 for(const x of [-1.2,1.2]){ctx.strokeStyle='#f8fcff';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(proj(x,90).x,proj(x,90).y);ctx.lineTo(proj(x,-3).x,proj(x,-3).y);ctx.stroke()}
}
function drawGate(e,d){const p=proj(e.x,d),w=W*.405*p.t,h=H*.112*p.t;const hue=e.shootable?'#995be8':e.op==='+'&&e.value<0?'#eb5866':'#16bdd6';ctx.save();ctx.globalAlpha=.9;rect(p.x-w/2,p.y-h,w,h,hue,5);ctx.globalAlpha=1;ctx.strokeStyle='#ffffff90';ctx.lineWidth=2;ctx.strokeRect(p.x-w/2,p.y-h,w,h);text((e.op==='+'&&e.value<0?'':e.op)+e.value,p.x,p.y-h*.56,31*p.t);if(e.shootable)text('射击 +1',p.x,p.y-h*.18,12*p.t,'#ffe27a');ctx.strokeStyle='#427e9f';ctx.lineWidth=4*p.t;ctx.beginPath();ctx.moveTo(p.x-w/2,p.y);ctx.lineTo(p.x-w/2,p.y+14*p.t);ctx.moveTo(p.x+w/2,p.y);ctx.lineTo(p.x+w/2,p.y+14*p.t);ctx.stroke();ctx.restore()}
function crowd(x,d,count,enemy=false){const visual=Math.min(90,count),cols=Math.max(2,Math.min(10,Math.ceil(Math.sqrt(visual)))),rows=Math.ceil(visual/cols);for(let row=rows-1;row>=0;row--){for(let col=0;col<cols;col++){const i=row*cols+col;if(i>=visual)continue;const xx=E.clamp(x+(col-(cols-1)/2)*.074,-1.08,1.08),p=proj(xx,d+row*.34);sprite(enemy?'enemy':'soldier',p.x,p.y+Math.sin(state.time*12+i)*1.2*p.t,W*.057*p.t)}}}
function drawEntity(e){const d=e.z-state.progress;if(d<0||d>90||e.dead)return;const p=proj(e.x,d);if(e.type==='gate'){drawGate(e,d);return}if(e.type==='enemy'){crowd(e.x,d,e.count,true);text(Math.ceil(e.hp),p.x,p.y-55*p.t,22*p.t,'#fff');return}sprite(e.type,p.x,p.y,W*(e.type==='boss'?.4:.16)*p.t);text(Math.ceil(e.hp),p.x,p.y-(e.type==='boss'?W*.42:W*.2)*p.t,20*p.t,e.type==='crate'?'#ffd85c':'#fff');if(e.type==='crate')text({rapid:'射速',spread:'散射',power:'伤害'}[e.reward],p.x,p.y+12*p.t,13*p.t,'#ffe180')}
function draw(){drawRoad();for(const a of state.attacks){const p=proj(a.x,0),l=proj(a.x-a.width,0),r=proj(a.x+a.width,0);ctx.fillStyle='rgba(255,38,70,'+(.18+.2*Math.sin(state.time*18)**2)+')';ctx.beginPath();ctx.ellipse(p.x,p.y-12,(r.x-l.x)/2,48,0,0,Math.PI*2);ctx.fill();text('⚠',p.x,p.y-25,26,'#ff5267');ctx.strokeStyle='#ff405e';ctx.lineWidth=4;ctx.beginPath();ctx.arc(p.x,p.y-12,25,-Math.PI/2,-Math.PI/2+(1-a.life/a.max)*Math.PI*2);ctx.stroke()}
 for(const e of state.entities.filter(e=>!e.dead).sort((a,b)=>b.z-a.z))drawEntity(e);
 ctx.save();ctx.shadowBlur=7;ctx.shadowColor='#ffbe3d';for(const b of state.bullets){const p=proj(b.x,b.z-state.progress);ctx.strokeStyle='#ffdc52';ctx.lineWidth=3*p.t+1;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x,p.y+15*p.t);ctx.stroke()}ctx.restore();
 crowd(state.x,0,state.count);const pp=proj(state.x,0);rect(pp.x-25,pp.y+6,50,28,'#147cce',8);text(state.count,pp.x,pp.y+20,20);
 for(const e of state.effects){const p=proj(e.x,e.z-state.progress);if(e.type==='spark'){ctx.fillStyle='#fff49c';ctx.beginPath();ctx.arc(p.x,p.y-12,6*p.t,0,7);ctx.fill()}else if(e.type==='hit'){ctx.fillStyle='#ff385c44';ctx.fillRect(0,0,W,H)}else{ctx.save();ctx.globalAlpha=Math.min(1,e.life*2);ctx.fillStyle='#ffbb38';ctx.beginPath();ctx.arc(p.x,p.y-15,(1-e.life/.6)*70*p.t,0,7);ctx.fill();ctx.fillStyle='#ffe99d';ctx.beginPath();ctx.arc(p.x,p.y-15,(1-e.life/.6)*37*p.t,0,7);ctx.fill();ctx.restore()}}
}
function beep(f=440,d=.06){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=f;o.type='triangle';g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.start();o.stop(audio.currentTime+d)}catch{}}
function fmt(t){return String(Math.floor(t/60)).padStart(2,'0')+':'+String(Math.floor(t%60)).padStart(2,'0')}
function hud(){$('levelName').textContent='行动 '+String(level).padStart(2,'0')+' · '+region[Math.floor((level-1)/6)];$('squad').innerHTML=state.count+' <span>人</span>';$('damage').textContent=Math.round(state.power*100)+'%';$('rate').textContent=Math.round(state.rate*100)+'%';$('spread').textContent=state.spread;$('kills').textContent=state.kills;$('peak').textContent=state.peak;$('time').textContent=fmt(state.time);$('progress').style.width=Math.min(100,state.progress/178*100)+'%';$('weaponName').textContent=state.spread>1?'散射步枪':state.rate>1?'速射步枪':'标准步枪';$('toast').replaceChildren(...state.notices.slice(-2).map(n=>{const el=document.createElement('span');el.textContent=n.text;el.style.color={blue:'#efffff',red:'#ffabb5',gold:'#ffe17c'}[n.color];el.style.opacity=Math.min(1,n.life*2);return el}));$('bossHud').hidden=!state.boss;const boss=state.entities.find(e=>e.type==='boss');$('bossName').textContent=level<=6?'铁甲巨人':level<=12?'赤焰统领':level<=18?'冰原破坏者':'要塞终结者';$('bossHp').textContent=Math.max(0,Math.ceil(boss.hp))+' / '+Math.ceil(boss.max);$('bossBar').style.width=Math.max(0,boss.hp/boss.max*100)+'%'}
function result(){if(finished)return;finished=true;$('pause').disabled=true;$('overlay').hidden=false;$('hint').hidden=true;const won=state.status==='won';if(won){unlocked=Math.min(24,Math.max(unlocked,level+1));try{localStorage.setItem('fire-squad-unlocked',unlocked)}catch{}beep(880,.25)}$('overlay').querySelector('.badge').textContent=won?'行动完成':'小队覆灭';$('overlay').querySelector('h2').textContent=won?(level===24?'全线突破！':'首领击破！'):'再集结，再出发';$('overlayText').textContent=won?'你的小队成功冲破了这条防线。':'试试先增援，再瞄准补给和数字门。';$('startStats').innerHTML='<span><b>'+state.kills+'</b>击破敌人</span><span><b>'+state.peak+'</b>最大队伍</span><span><b>'+fmt(state.time)+'</b>用时</span>';$('start').textContent=won&&level<24?'下一关 · 继续推进':'再战一次';$('start').dataset.next=won&&level<24?'yes':'no';$('startHint').textContent='关卡 '+level+' / 24 · '+region[Math.floor((level-1)/6)]}
function start(){if($('start').dataset.next==='yes'){level=Math.min(24,level+1)}state=E.create(level);state.status='running';finished=false;oldKill=0;$('overlay').hidden=true;$('levels').hidden=true;$('pause').disabled=false;$('pause').textContent='暂停';$('hint').hidden=false;c.focus();keys.clear();beep(660,.1)}$('start').onclick=start;
function pause(){if(state.status==='running'){state.status='paused';$('pause').textContent='继续';$('hint').textContent='已暂停 · 点击继续'}else if(state.status==='paused'){state.status='running';$('pause').textContent='暂停';$('hint').textContent='左右拖动 · 自动开火';c.focus()}}$('pause').onclick=pause;
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.status==='running')pause()});window.addEventListener('blur',()=>{keys.clear();if(state.status==='running')pause()});
$('sound').onclick=()=>{sound=!sound;$('sound').textContent='音效：'+(sound?'开':'关');beep()};
function grid(){$('levelGrid').replaceChildren();for(let n=1;n<=24;n++){const b=document.createElement('button');b.textContent=String(n).padStart(2,'0');b.disabled=n>unlocked;b.className=n===level?'current':'';b.setAttribute('aria-label','关卡 '+n+(n>unlocked?'，尚未解锁':''));b.onclick=()=>{level=n;state=E.create(level);$('levels').hidden=true;finished=false;$('start').dataset.next='no';$('start').textContent='开始行动';$('overlay').querySelector('h2').textContent='火力小队';$('overlay').querySelector('.badge').textContent='行动准备';$('overlayText').textContent=region[Math.floor((level-1)/6)]+' · 行动 '+String(level).padStart(2,'0');$('startStats').innerHTML='<span><b>8</b>初始队员</span><span><b>'+n+'</b>当前关卡</span>';hud()};$('levelGrid').append(b)}}$('selectLevel').onclick=()=>{grid();$('levels').hidden=false};$('back').onclick=()=>{$('levels').hidden=true};
function pointerX(ev){const r=c.getBoundingClientRect();state.target=E.clamp((ev.clientX-r.left-r.width/2)/(r.width*.435),-.85,.85)}c.addEventListener('pointerdown',ev=>{if(state.status!=='running')return;pointer=ev.pointerId;c.setPointerCapture(pointer);pointerX(ev)});c.addEventListener('pointermove',ev=>{if(ev.pointerId===pointer)pointerX(ev)});for(const name of ['pointerup','pointercancel'])c.addEventListener(name,()=>pointer=null);
window.addEventListener('keydown',ev=>{if(['ArrowLeft','ArrowRight','a','d','A','D',' '].includes(ev.key)&&state.status!=='ready'){ev.preventDefault();if(ev.key===' '&&!ev.repeat){pause();return}keys.add(ev.key)}});window.addEventListener('keyup',ev=>keys.delete(ev.key));
let htime=0,oldKill=0;function loop(now){let dt=Math.min((now-last)/1000||0,.05);last=now;if(state.status==='running'){const left=keys.has('ArrowLeft')||keys.has('a')||keys.has('A'),right=keys.has('ArrowRight')||keys.has('d')||keys.has('D');if(left||right)state.target=E.clamp(state.target+((right?1:0)-(left?1:0))*dt*2.2,-.85,.85);E.step(state,dt);if(state.kills>oldKill){beep(260,.07);oldKill=state.kills}if(state.status==='lost'||state.status==='won')result()}draw();htime+=dt;if(htime>.08){hud();htime=0}requestAnimationFrame(loop)}hud();requestAnimationFrame(loop);
